# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: npm install
    - name: create postgresql tables
      run: PGPASSWORD=codex123 psql -h localhost -U codex -d restuarant_bookings -a -f ./sql/tables.sql
    - name: populate data into table
      run: PGPASSWORD=codex123 psql -h localhost -U codex -d restuarant_bookings -a -f ./sql/data.sql
      env:
        DATABASE_URL: postgres://wgpxzziz:BTUTk57yJU9dDzV_JVfBQ52EnXsXCWf7@dumbo.db.elephantsql.com/wgpxzziz?ssl=true
